version: "3"

services:
  subscription-database:
    image: library/postgres:14
    container_name: subscriptiontestdb
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'postgres'
    ports:
      - "5435:5432"
  freeusers-database:
    image: library/postgres:14
    container_name: freeusertestdb
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'postgres'
    ports:
      - "5436:5432"